export const BULLISH_KEYWORDS: Array<{ word: string; weight: number }> = [
  { word: 'etf approved', weight: 2.0 },
  { word: 'etf approval', weight: 2.0 },
  { word: 'institutional buy', weight: 2.0 },
  { word: 'all-time high', weight: 2.0 },
  { word: 'ath', weight: 1.8 },
  { word: 'short squeeze', weight: 1.8 },
  { word: 'massive adoption', weight: 1.8 },
  { word: 'bullish', weight: 1.0 },
  { word: 'rally', weight: 1.0 },
  { word: 'surge', weight: 1.0 },
  { word: 'breakout', weight: 1.0 },
  { word: 'moon', weight: 0.8 },
  { word: 'pump', weight: 0.8 },
  { word: 'adoption', weight: 1.0 },
  { word: 'partnership', weight: 0.9 },
  { word: 'upgrade', weight: 0.9 },
  { word: 'launch', weight: 0.7 },
  { word: 'record', weight: 0.8 },
  { word: 'accumulation', weight: 1.0 },
  { word: 'inflow', weight: 0.9 },
  { word: 'buy', weight: 0.5 },
  { word: 'long', weight: 0.4 },
  { word: 'recovery', weight: 0.7 },
  { word: 'rebound', weight: 0.8 },
  { word: 'support', weight: 0.6 },
  { word: 'demand', weight: 0.7 },
  { word: 'optimism', weight: 0.8 },
  { word: 'positive', weight: 0.5 },
  { word: 'growth', weight: 0.6 },
  { word: 'profit', weight: 0.6 },
  { word: 'gain', weight: 0.6 },
  { word: 'рост', weight: 0.8 },
  { word: 'буллиш', weight: 1.0 },
  { word: 'покупка', weight: 0.6 },
  { word: 'одобрение', weight: 1.2 },
  { word: 'партнёрство', weight: 0.9 },
  { word: 'запуск', weight: 0.7 },
  { word: 'рекорд', weight: 0.8 },
]

export const BEARISH_KEYWORDS: Array<{ word: string; weight: number }> = [
  { word: 'sec lawsuit', weight: 2.0 },
  { word: 'exchange hack', weight: 2.0 },
  { word: 'bankruptcy', weight: 2.0 },
  { word: 'collapse', weight: 2.0 },
  { word: 'total ban', weight: 2.0 },
  { word: 'market crash', weight: 2.0 },
  { word: 'ponzi', weight: 2.0 },
  { word: 'bearish', weight: 1.0 },
  { word: 'crash', weight: 1.2 },
  { word: 'dump', weight: 1.0 },
  { word: 'sell', weight: 0.5 },
  { word: 'ban', weight: 1.2 },
  { word: 'hack', weight: 1.5 },
  { word: 'vulnerability', weight: 1.3 },
  { word: 'lawsuit', weight: 1.3 },
  { word: 'regulation', weight: 0.7 },
  { word: 'fine', weight: 0.9 },
  { word: 'liquidation', weight: 1.0 },
  { word: 'scam', weight: 1.5 },
  { word: 'fraud', weight: 1.5 },
  { word: 'fear', weight: 0.7 },
  { word: 'outflow', weight: 0.9 },
  { word: 'resistance', weight: 0.5 },
  { word: 'warning', weight: 0.7 },
  { word: 'concern', weight: 0.5 },
  { word: 'risk', weight: 0.4 },
  { word: 'loss', weight: 0.7 },
  { word: 'decline', weight: 0.8 },
  { word: 'drop', weight: 0.8 },
  { word: 'plunge', weight: 1.0 },
  { word: 'plummet', weight: 1.0 },
  { word: 'падение', weight: 0.8 },
  { word: 'бан', weight: 1.2 },
  { word: 'запрет', weight: 1.2 },
  { word: 'мошенничество', weight: 1.5 },
  { word: 'взлом', weight: 1.5 },
  { word: 'банкротство', weight: 2.0 },
  { word: 'иск', weight: 1.0 },
]

export const SOURCE_WEIGHTS: Record<string, number> = {
  reuters: 2.0,
  bloomberg: 2.0,
  coindesk: 1.5,
  cointelegraph: 1.3,
  theblock: 1.3,
  decrypt: 1.1,
  cryptopanic: 0.9,
  unknown: 0.7,
}
